### ISSUE TITLE
Agent initiated chat

### ISSUE THREAD

**Issue by ska-ibees** [twilio/twilio-webchat-react-app#16]
Is there any option for the agent to see current visitors on the website and to initiate a chat rather than waiting for the visitor to start a conversation?

**Comment by raffaele-abramini** [comment]
Hey @ska-ibees , I'm afraid that no, this functionality doesn't come out of the box with this widget.

What would the use-case be?

**Comment by ska-ibees** [comment]
Hey,

Actually, it is  a requirement from the marketing/sales that agents
proactively need to monitor website visitors and offer them help based on
the page/product they are interested in.

For higher conversions they want to engage with each and every visitor on
the site by initiating chat from backend/monitoring dashboard instead of
waiting visitor to start session.

By the way, this is not something new. It has been a default feature
offered by Zopim/Zendesk and probably Tawk.to

Hope it makes sense.

**Comment by raffaele-abramini** [comment]
Great, thanks for sharing!

As I mentioned this feature doesn't come out of the box and, as far as I know, it's not in the pipeline. In general, we aim to keep this starter project rather nimble. Having said that, if things changes I'll let you know.

Anyway, this feature can be potentially achieved. Now, you _could_ generate a Converastion and a Task automatically every time a customer joins the website, but that would become rather expensive. A more efficient solution would be to potentially introduce a service that keeps track of how long a customer has been  on the website and maybe start the conversation with them after they've been on the page for a certain amount of time.

**Comment by raffaele-abramini** [comment]
We marked this as potential area to explore, closing this thread.
